### ISSUE TITLE
Incorrect type used for zone serial number.

### ISSUE THREAD

**Issue by bartelsielski** [ffledgling/pdns-go#1]
The Serial field of the Zone struct is set to the incorrect type (int32, while it should be uint32).

According to [RFC1035 section 3.3.13](https://tools.ietf.org/html/rfc1035#section-3.3.13) the serial number of a SOA resource record is a 32 bit unsigned integer.

This causes the following error when the serial number is larger than 2^31-1:
```
json: cannot unmarshal number 3531147737 into Go struct field Zone.serial of type int32
```

**Comment by ffledgling** [comment]
Thank for finding and filing this bug. I've looked into it briefly and at first glance it appears that the fix for this is tricky, because the swagger spec (from which this library is generated - https://github.com/PowerDNS/pdns/blob/master/docs/http-api/swagger/authoritative-api-swagger.yaml) does not support the uint family of datatypes (https://swagger.io/docs/specification/data-models/data-types/). I'll try digging in a bit more to see if there's a work around.

**Comment by bartelsielski** [comment]
Wouldn't it be possible to use the minimum and maximum keywords to limit it from `0` to `2^32-1`? 
The content of the swagger definition would then look like this:
```
serial:
  type: integer
  format: int64
  minimum: 0
  maximum: 4294967295
  description: 'The SOA serial number'
notified_serial:
  type: integer
  format: int64
  minimum: 0
  maximum: 4294967295
  description: 'The SOA serial notifications have been sent out for'
```
